### ISSUE TITLE
Checkmarx vulnerability scan

### ISSUE THREAD

**Issue by sumeetisp** [baruchel/txt2pdf#11]
We found vulnerability in check marx scan for txt2pdf.py. Following are the details,

Method __init__ at line 42 of txt2pdf.py sends user information outside the application. This may constitute a Privacy Violation.

Will this be fixed in future releases?

**Comment by clach04** [comment]
@sumeetisp  I don't see anything like that on line 42 - https://github.com/baruchel/txt2pdf/blob/63a08bf0c399cf48fc3bfea2cdad4fbd93642440/txt2pdf.py#L42 . Please update with a link. Thanks!

**Comment by clach04** [comment]
Closed as this does not appear to be a problem today. re-open if needed.
