### ISSUE TITLE
HINT:  Piping - Make my own Documentation

### ISSUE THREAD

**Issue by afgcons** [baruchel/txt2pdf#13]
txt2pdf -h | txt2pdf /dev/stdin -o txt2pdf_help.pdf

sudo fdisk -l | txt2pdf /dev/stdin -o disks.pdf

/dev/stdin  as text input file name is working (as expected) !
txt2pdf.py copied to /usr/local/bin as txt2pdf

**Comment by clach04** [comment]
Neat, linked to in the wiki https://github.com/baruchel/txt2pdf/wiki#using-pipes - closing.
